export const closetTypes='/closet/types'
export const closetRecords='/closet/records'

export const closetConfigLocation='/closet/config/location'
export const closetConfigTypes='/closet/config/types'
export const closetConfigBrand='/closet/config/brand'
export const closetConfigBrands='/closet/config/brands'
export const closetConfigBrandsGroup='/closet/config/brandsGroup'
export const closetTypeGroup='/closetType/group'
export const clockIn='/clock/in'